name: gravity_field
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy=2.2.6
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - threadpoolctl=3.5.0
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pyarrow=21.0.0
  - pip
  - pip:
      - pyshtools>=4.13.1
      - cartopy==0.25.0
      - lightning>=2.3.0
      - wandb